/**
 * generated by http://RDFReactor.semweb4j.org ($Id: CodeGenerator.java 1535 2008-09-09 15:44:46Z max.at.xam.de $) on 29.10.13 09:05
 */
package org.purl.rvl.interpreter.rvl;

import org.ontoware.aifbcommons.collection.ClosableIterator;
import org.ontoware.rdf2go.exception.ModelRuntimeException;
import org.ontoware.rdf2go.model.Model;
import org.ontoware.rdf2go.model.node.BlankNode;
import org.ontoware.rdf2go.model.node.URI;
import org.ontoware.rdf2go.model.node.impl.URIImpl;
import org.ontoware.rdfreactor.runtime.Base;
import org.ontoware.rdfreactor.runtime.ReactorResult;

/**
 * This class manages access to these properties:
 * <ul>
 *   <li> Lowerboundexclusive </li>
 *   <li> Lowerboundinclusive </li>
 *   <li> Upperboundexclusive </li>
 *   <li> Upperboundinclusive </li>
 * </ul>
 *
 * This class was generated by <a href="http://RDFReactor.semweb4j.org">RDFReactor</a> on 29.10.13 09:05
 */
public class Interval extends Thing {

    /** http://purl.org/rvl/Interval */
    @SuppressWarnings("hiding")
	public static final URI RDFS_CLASS = new URIImpl("http://purl.org/rvl/Interval", false);

    /** http://purl.org/rvl/lowerBoundExcl */
    @SuppressWarnings("hiding")
	public static final URI LOWERBOUNDEXCLUSIVE = new URIImpl("http://purl.org/rvl/lowerBoundExcl",false);

    /** http://purl.org/rvl/lowerBoundIncl */
    @SuppressWarnings("hiding")
	public static final URI LOWERBOUNDINCLUSIVE = new URIImpl("http://purl.org/rvl/lowerBoundIncl",false);

    /** http://purl.org/rvl/upperBoundExcl */
    @SuppressWarnings("hiding")
	public static final URI UPPERBOUNDEXCLUSIVE = new URIImpl("http://purl.org/rvl/upperBoundExcl",false);

    /** http://purl.org/rvl/upperBoundIncl */
    @SuppressWarnings("hiding")
	public static final URI UPPERBOUNDINCLUSIVE = new URIImpl("http://purl.org/rvl/upperBoundIncl",false);

    /** 
     * All property-URIs with this class as domain.
     * All properties of all super-classes are also available. 
     */
    @SuppressWarnings("hiding")
    public static final URI[] MANAGED_URIS = {
      new URIImpl("http://purl.org/rvl/lowerBoundExcl",false),
      new URIImpl("http://purl.org/rvl/lowerBoundIncl",false),
      new URIImpl("http://purl.org/rvl/upperBoundExcl",false),
      new URIImpl("http://purl.org/rvl/upperBoundIncl",false) 
    };


	// protected constructors needed for inheritance
	
	/**
	 * Returns a Java wrapper over an RDF object, identified by URI.
	 * Creating two wrappers for the same instanceURI is legal.
	 * @param model RDF2GO Model implementation, see http://rdf2go.semweb4j.org
	 * @param classURI URI of RDFS class
	 * @param instanceIdentifier Resource that identifies this instance
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 *
	 * [Generated from RDFReactor template rule #c1] 
	 */
	protected Interval ( Model model, URI classURI, org.ontoware.rdf2go.model.node.Resource instanceIdentifier, boolean write ) {
		super(model, classURI, instanceIdentifier, write);
	}

	// public constructors

	/**
	 * Returns a Java wrapper over an RDF object, identified by URI.
	 * Creating two wrappers for the same instanceURI is legal.
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param instanceIdentifier an RDF2Go Resource identifying this instance
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 *
	 * [Generated from RDFReactor template rule #c2] 
	 */
	public Interval ( Model model, org.ontoware.rdf2go.model.node.Resource instanceIdentifier, boolean write ) {
		super(model, RDFS_CLASS, instanceIdentifier, write);
	}


	/**
	 * Returns a Java wrapper over an RDF object, identified by a URI, given as a String.
	 * Creating two wrappers for the same URI is legal.
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param uriString a URI given as a String
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 * @throws ModelRuntimeException if URI syntax is wrong
	 *
	 * [Generated from RDFReactor template rule #c7] 
	 */
	public Interval ( Model model, String uriString, boolean write) throws ModelRuntimeException {
		super(model, RDFS_CLASS, new URIImpl(uriString,false), write);
	}

	/**
	 * Returns a Java wrapper over an RDF object, identified by a blank node.
	 * Creating two wrappers for the same blank node is legal.
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param bnode BlankNode of this instance
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 *
	 * [Generated from RDFReactor template rule #c8] 
	 */
	public Interval ( Model model, BlankNode bnode, boolean write ) {
		super(model, RDFS_CLASS, bnode, write);
	}

	/**
	 * Returns a Java wrapper over an RDF object, identified by 
	 * a randomly generated URI.
	 * Creating two wrappers results in different URIs.
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 *
	 * [Generated from RDFReactor template rule #c9] 
	 */
	public Interval ( Model model, boolean write ) {
		super(model, RDFS_CLASS, model.newRandomUniqueURI(), write);
	}

    ///////////////////////////////////////////////////////////////////
    // typing

	/**
	 * Return an existing instance of this class in the model. No statements are written.
	 * @param model an RDF2Go model
	 * @param instanceResource an RDF2Go resource
	 * @return an instance of Interval  or null if none existst
	 *
	 * [Generated from RDFReactor template rule #class0] 
	 */
	public static Interval  getInstance(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getInstance(model, instanceResource, Interval.class);
	}

	/**
	 * Create a new instance of this class in the model. 
	 * That is, create the statement (instanceResource, RDF.type, http://purl.org/rvl/Interval).
	 * @param model an RDF2Go model
	 * @param instanceResource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #class1] 
	 */
	public static void createInstance(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		Base.createInstance(model, RDFS_CLASS, instanceResource);
	}

	/**
	 * @param model an RDF2Go model
	 * @param instanceResource an RDF2Go resource
	 * @return true if instanceResource is an instance of this class in the model
	 *
	 * [Generated from RDFReactor template rule #class2] 
	 */
	public static boolean hasInstance(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.hasInstance(model, RDFS_CLASS, instanceResource);
	}

	/**
	 * @param model an RDF2Go model
	 * @return all instances of this class in Model 'model' as RDF resources
	 *
	 * [Generated from RDFReactor template rule #class3] 
	 */
	public static ClosableIterator<org.ontoware.rdf2go.model.node.Resource> getAllInstances(Model model) {
		return Base.getAllInstances(model, RDFS_CLASS, org.ontoware.rdf2go.model.node.Resource.class);
	}

	/**
	 * @param model an RDF2Go model
	 * @return all instances of this class in Model 'model' as a ReactorResult,
	 * which can conveniently be converted to iterator, list or array.
	 *
	 * [Generated from RDFReactor template rule #class3-as] 
	 */
	public static ReactorResult<? extends Interval> getAllInstances_as(Model model) {
		return Base.getAllInstances_as(model, RDFS_CLASS, Interval.class );
	}

    /**
	 * Remove rdf:type Interval from this instance. Other triples are not affected.
	 * To delete more, use deleteAllProperties
	 * @param model an RDF2Go model
	 * @param instanceResource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #class4] 
	 */
	public static void deleteInstance(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		Base.deleteInstance(model, RDFS_CLASS, instanceResource);
	}

	/**
	 * Delete all (this, *, *), i.e. including rdf:type
	 * @param model an RDF2Go model
	 * @param resource
	 */
	public static void deleteAllProperties(Model model,	org.ontoware.rdf2go.model.node.Resource instanceResource) {
		Base.deleteAllProperties(model, instanceResource);
	}

    ///////////////////////////////////////////////////////////////////
    // property access methods


    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@47baec4c has at least one value set 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return true if this property has at least one value
	 *
	 * [Generated from RDFReactor template rule #get0has-static] 
     */
	public static boolean hasLowerboundexclusive(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.has(model, instanceResource, LOWERBOUNDEXCLUSIVE);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@47baec4c has at least one value set 
     * @return true if this property has at least one value
	 *
	 * [Generated from RDFReactor template rule #get0has-dynamic] 
     */
	public boolean hasLowerboundexclusive() {
		return Base.has(this.model, this.getResource(), LOWERBOUNDEXCLUSIVE);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@47baec4c has the given value (maybe among other values).  
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be checked
     * @return true if this property contains (maybe among other) the given value
	 *
	 * [Generated from RDFReactor template rule #get0has-value-static] 
     */
	public static boolean hasLowerboundexclusive(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value ) {
		return Base.hasValue(model, instanceResource, LOWERBOUNDEXCLUSIVE);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@47baec4c has the given value (maybe among other values).  
	 * @param value the value to be checked
     * @return true if this property contains (maybe among other) the given value
	 *
	 * [Generated from RDFReactor template rule #get0has-value-dynamic] 
     */
	public boolean hasLowerboundexclusive( org.ontoware.rdf2go.model.node.Node value ) {
		return Base.hasValue(this.model, this.getResource(), LOWERBOUNDEXCLUSIVE);
	}

     /**
     * Get all values of property Lowerboundexclusive as an Iterator over RDF2Go nodes 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ClosableIterator of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get7static] 
     */
	public static ClosableIterator<org.ontoware.rdf2go.model.node.Node> getAllLowerboundexclusive_asNode(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_asNode(model, instanceResource, LOWERBOUNDEXCLUSIVE);
	}
	
    /**
     * Get all values of property Lowerboundexclusive as a ReactorResult of RDF2Go nodes 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a List of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get7static-reactor-result] 
     */
	public static ReactorResult<org.ontoware.rdf2go.model.node.Node> getAllLowerboundexclusive_asNode_(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_as(model, instanceResource, LOWERBOUNDEXCLUSIVE, org.ontoware.rdf2go.model.node.Node.class);
	}

    /**
     * Get all values of property Lowerboundexclusive as an Iterator over RDF2Go nodes 
     * @return a ClosableIterator of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get8dynamic] 
     */
	public ClosableIterator<org.ontoware.rdf2go.model.node.Node> getAllLowerboundexclusive_asNode() {
		return Base.getAll_asNode(this.model, this.getResource(), LOWERBOUNDEXCLUSIVE);
	}

    /**
     * Get all values of property Lowerboundexclusive as a ReactorResult of RDF2Go nodes 
     * @return a List of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get8dynamic-reactor-result] 
     */
	public ReactorResult<org.ontoware.rdf2go.model.node.Node> getAllLowerboundexclusive_asNode_() {
		return Base.getAll_as(this.model, this.getResource(), LOWERBOUNDEXCLUSIVE, org.ontoware.rdf2go.model.node.Node.class);
	}
     /**
     * Get all values of property Lowerboundexclusive     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ClosableIterator of $type
	 *
	 * [Generated from RDFReactor template rule #get11static] 
     */
	public static ClosableIterator<Thing> getAllLowerboundexclusive(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll(model, instanceResource, LOWERBOUNDEXCLUSIVE, Thing.class);
	}
	
    /**
     * Get all values of property Lowerboundexclusive as a ReactorResult of Thing 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ReactorResult of $type which can conveniently be converted to iterator, list or array
	 *
	 * [Generated from RDFReactor template rule #get11static-reactorresult] 
     */
	public static ReactorResult<Thing> getAllLowerboundexclusive_as(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_as(model, instanceResource, LOWERBOUNDEXCLUSIVE, Thing.class);
	}

    /**
     * Get all values of property Lowerboundexclusive     * @return a ClosableIterator of $type
	 *
	 * [Generated from RDFReactor template rule #get12dynamic] 
     */
	public ClosableIterator<Thing> getAllLowerboundexclusive() {
		return Base.getAll(this.model, this.getResource(), LOWERBOUNDEXCLUSIVE, Thing.class);
	}

    /**
     * Get all values of property Lowerboundexclusive as a ReactorResult of Thing 
     * @return a ReactorResult of $type which can conveniently be converted to iterator, list or array
	 *
	 * [Generated from RDFReactor template rule #get12dynamic-reactorresult] 
     */
	public ReactorResult<Thing> getAllLowerboundexclusive_as() {
		return Base.getAll_as(this.model, this.getResource(), LOWERBOUNDEXCLUSIVE, Thing.class);
	}
 
    /**
     * Adds a value to property Lowerboundexclusive as an RDF2Go node 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #add1static] 
     */
	public static void addLowerboundexclusive( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.add(model, instanceResource, LOWERBOUNDEXCLUSIVE, value);
	}
	
    /**
     * Adds a value to property Lowerboundexclusive as an RDF2Go node 
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #add1dynamic] 
     */
	public void addLowerboundexclusive( org.ontoware.rdf2go.model.node.Node value) {
		Base.add(this.model, this.getResource(), LOWERBOUNDEXCLUSIVE, value);
	}
    /**
     * Adds a value to property Lowerboundexclusive from an instance of Thing 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #add3static] 
     */
	public static void addLowerboundexclusive(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, Thing value) {
		Base.add(model, instanceResource, LOWERBOUNDEXCLUSIVE, value);
	}
	
    /**
     * Adds a value to property Lowerboundexclusive from an instance of Thing 
	 *
	 * [Generated from RDFReactor template rule #add4dynamic] 
     */
	public void addLowerboundexclusive(Thing value) {
		Base.add(this.model, this.getResource(), LOWERBOUNDEXCLUSIVE, value);
	}
  

    /**
     * Sets a value of property Lowerboundexclusive from an RDF2Go node.
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be set
	 *
	 * [Generated from RDFReactor template rule #set1static] 
     */
	public static void setLowerboundexclusive( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.set(model, instanceResource, LOWERBOUNDEXCLUSIVE, value);
	}
	
    /**
     * Sets a value of property Lowerboundexclusive from an RDF2Go node.
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set1dynamic] 
     */
	public void setLowerboundexclusive( org.ontoware.rdf2go.model.node.Node value) {
		Base.set(this.model, this.getResource(), LOWERBOUNDEXCLUSIVE, value);
	}
    /**
     * Sets a value of property Lowerboundexclusive from an instance of Thing 
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set3static] 
     */
	public static void setLowerboundexclusive(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, Thing value) {
		Base.set(model, instanceResource, LOWERBOUNDEXCLUSIVE, value);
	}
	
    /**
     * Sets a value of property Lowerboundexclusive from an instance of Thing 
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set4dynamic] 
     */
	public void setLowerboundexclusive(Thing value) {
		Base.set(this.model, this.getResource(), LOWERBOUNDEXCLUSIVE, value);
	}
  


    /**
     * Removes a value of property Lowerboundexclusive as an RDF2Go node 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove1static] 
     */
	public static void removeLowerboundexclusive( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.remove(model, instanceResource, LOWERBOUNDEXCLUSIVE, value);
	}
	
    /**
     * Removes a value of property Lowerboundexclusive as an RDF2Go node
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove1dynamic] 
     */
	public void removeLowerboundexclusive( org.ontoware.rdf2go.model.node.Node value) {
		Base.remove(this.model, this.getResource(), LOWERBOUNDEXCLUSIVE, value);
	}
    /**
     * Removes a value of property Lowerboundexclusive given as an instance of Thing 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove3static] 
     */
	public static void removeLowerboundexclusive(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, Thing value) {
		Base.remove(model, instanceResource, LOWERBOUNDEXCLUSIVE, value);
	}
	
    /**
     * Removes a value of property Lowerboundexclusive given as an instance of Thing 
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove4dynamic] 
     */
	public void removeLowerboundexclusive(Thing value) {
		Base.remove(this.model, this.getResource(), LOWERBOUNDEXCLUSIVE, value);
	}
  
    /**
     * Removes all values of property Lowerboundexclusive     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #removeall1static] 
     */
	public static void removeAllLowerboundexclusive( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		Base.removeAll(model, instanceResource, LOWERBOUNDEXCLUSIVE);
	}
	
    /**
     * Removes all values of property Lowerboundexclusive	 *
	 * [Generated from RDFReactor template rule #removeall1dynamic] 
     */
	public void removeAllLowerboundexclusive() {
		Base.removeAll(this.model, this.getResource(), LOWERBOUNDEXCLUSIVE);
	}
     /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@3fecf56a has at least one value set 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return true if this property has at least one value
	 *
	 * [Generated from RDFReactor template rule #get0has-static] 
     */
	public static boolean hasLowerboundinclusive(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.has(model, instanceResource, LOWERBOUNDINCLUSIVE);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@3fecf56a has at least one value set 
     * @return true if this property has at least one value
	 *
	 * [Generated from RDFReactor template rule #get0has-dynamic] 
     */
	public boolean hasLowerboundinclusive() {
		return Base.has(this.model, this.getResource(), LOWERBOUNDINCLUSIVE);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@3fecf56a has the given value (maybe among other values).  
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be checked
     * @return true if this property contains (maybe among other) the given value
	 *
	 * [Generated from RDFReactor template rule #get0has-value-static] 
     */
	public static boolean hasLowerboundinclusive(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value ) {
		return Base.hasValue(model, instanceResource, LOWERBOUNDINCLUSIVE);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@3fecf56a has the given value (maybe among other values).  
	 * @param value the value to be checked
     * @return true if this property contains (maybe among other) the given value
	 *
	 * [Generated from RDFReactor template rule #get0has-value-dynamic] 
     */
	public boolean hasLowerboundinclusive( org.ontoware.rdf2go.model.node.Node value ) {
		return Base.hasValue(this.model, this.getResource(), LOWERBOUNDINCLUSIVE);
	}

     /**
     * Get all values of property Lowerboundinclusive as an Iterator over RDF2Go nodes 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ClosableIterator of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get7static] 
     */
	public static ClosableIterator<org.ontoware.rdf2go.model.node.Node> getAllLowerboundinclusive_asNode(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_asNode(model, instanceResource, LOWERBOUNDINCLUSIVE);
	}
	
    /**
     * Get all values of property Lowerboundinclusive as a ReactorResult of RDF2Go nodes 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a List of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get7static-reactor-result] 
     */
	public static ReactorResult<org.ontoware.rdf2go.model.node.Node> getAllLowerboundinclusive_asNode_(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_as(model, instanceResource, LOWERBOUNDINCLUSIVE, org.ontoware.rdf2go.model.node.Node.class);
	}

    /**
     * Get all values of property Lowerboundinclusive as an Iterator over RDF2Go nodes 
     * @return a ClosableIterator of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get8dynamic] 
     */
	public ClosableIterator<org.ontoware.rdf2go.model.node.Node> getAllLowerboundinclusive_asNode() {
		return Base.getAll_asNode(this.model, this.getResource(), LOWERBOUNDINCLUSIVE);
	}

    /**
     * Get all values of property Lowerboundinclusive as a ReactorResult of RDF2Go nodes 
     * @return a List of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get8dynamic-reactor-result] 
     */
	public ReactorResult<org.ontoware.rdf2go.model.node.Node> getAllLowerboundinclusive_asNode_() {
		return Base.getAll_as(this.model, this.getResource(), LOWERBOUNDINCLUSIVE, org.ontoware.rdf2go.model.node.Node.class);
	}
     /**
     * Get all values of property Lowerboundinclusive     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ClosableIterator of $type
	 *
	 * [Generated from RDFReactor template rule #get11static] 
     */
	public static ClosableIterator<Thing> getAllLowerboundinclusive(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll(model, instanceResource, LOWERBOUNDINCLUSIVE, Thing.class);
	}
	
    /**
     * Get all values of property Lowerboundinclusive as a ReactorResult of Thing 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ReactorResult of $type which can conveniently be converted to iterator, list or array
	 *
	 * [Generated from RDFReactor template rule #get11static-reactorresult] 
     */
	public static ReactorResult<Thing> getAllLowerboundinclusive_as(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_as(model, instanceResource, LOWERBOUNDINCLUSIVE, Thing.class);
	}

    /**
     * Get all values of property Lowerboundinclusive     * @return a ClosableIterator of $type
	 *
	 * [Generated from RDFReactor template rule #get12dynamic] 
     */
	public ClosableIterator<Thing> getAllLowerboundinclusive() {
		return Base.getAll(this.model, this.getResource(), LOWERBOUNDINCLUSIVE, Thing.class);
	}

    /**
     * Get all values of property Lowerboundinclusive as a ReactorResult of Thing 
     * @return a ReactorResult of $type which can conveniently be converted to iterator, list or array
	 *
	 * [Generated from RDFReactor template rule #get12dynamic-reactorresult] 
     */
	public ReactorResult<Thing> getAllLowerboundinclusive_as() {
		return Base.getAll_as(this.model, this.getResource(), LOWERBOUNDINCLUSIVE, Thing.class);
	}
 
    /**
     * Adds a value to property Lowerboundinclusive as an RDF2Go node 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #add1static] 
     */
	public static void addLowerboundinclusive( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.add(model, instanceResource, LOWERBOUNDINCLUSIVE, value);
	}
	
    /**
     * Adds a value to property Lowerboundinclusive as an RDF2Go node 
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #add1dynamic] 
     */
	public void addLowerboundinclusive( org.ontoware.rdf2go.model.node.Node value) {
		Base.add(this.model, this.getResource(), LOWERBOUNDINCLUSIVE, value);
	}
    /**
     * Adds a value to property Lowerboundinclusive from an instance of Thing 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #add3static] 
     */
	public static void addLowerboundinclusive(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, Thing value) {
		Base.add(model, instanceResource, LOWERBOUNDINCLUSIVE, value);
	}
	
    /**
     * Adds a value to property Lowerboundinclusive from an instance of Thing 
	 *
	 * [Generated from RDFReactor template rule #add4dynamic] 
     */
	public void addLowerboundinclusive(Thing value) {
		Base.add(this.model, this.getResource(), LOWERBOUNDINCLUSIVE, value);
	}
  

    /**
     * Sets a value of property Lowerboundinclusive from an RDF2Go node.
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be set
	 *
	 * [Generated from RDFReactor template rule #set1static] 
     */
	public static void setLowerboundinclusive( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.set(model, instanceResource, LOWERBOUNDINCLUSIVE, value);
	}
	
    /**
     * Sets a value of property Lowerboundinclusive from an RDF2Go node.
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set1dynamic] 
     */
	public void setLowerboundinclusive( org.ontoware.rdf2go.model.node.Node value) {
		Base.set(this.model, this.getResource(), LOWERBOUNDINCLUSIVE, value);
	}
    /**
     * Sets a value of property Lowerboundinclusive from an instance of Thing 
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set3static] 
     */
	public static void setLowerboundinclusive(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, Thing value) {
		Base.set(model, instanceResource, LOWERBOUNDINCLUSIVE, value);
	}
	
    /**
     * Sets a value of property Lowerboundinclusive from an instance of Thing 
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set4dynamic] 
     */
	public void setLowerboundinclusive(Thing value) {
		Base.set(this.model, this.getResource(), LOWERBOUNDINCLUSIVE, value);
	}
  


    /**
     * Removes a value of property Lowerboundinclusive as an RDF2Go node 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove1static] 
     */
	public static void removeLowerboundinclusive( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.remove(model, instanceResource, LOWERBOUNDINCLUSIVE, value);
	}
	
    /**
     * Removes a value of property Lowerboundinclusive as an RDF2Go node
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove1dynamic] 
     */
	public void removeLowerboundinclusive( org.ontoware.rdf2go.model.node.Node value) {
		Base.remove(this.model, this.getResource(), LOWERBOUNDINCLUSIVE, value);
	}
    /**
     * Removes a value of property Lowerboundinclusive given as an instance of Thing 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove3static] 
     */
	public static void removeLowerboundinclusive(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, Thing value) {
		Base.remove(model, instanceResource, LOWERBOUNDINCLUSIVE, value);
	}
	
    /**
     * Removes a value of property Lowerboundinclusive given as an instance of Thing 
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove4dynamic] 
     */
	public void removeLowerboundinclusive(Thing value) {
		Base.remove(this.model, this.getResource(), LOWERBOUNDINCLUSIVE, value);
	}
  
    /**
     * Removes all values of property Lowerboundinclusive     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #removeall1static] 
     */
	public static void removeAllLowerboundinclusive( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		Base.removeAll(model, instanceResource, LOWERBOUNDINCLUSIVE);
	}
	
    /**
     * Removes all values of property Lowerboundinclusive	 *
	 * [Generated from RDFReactor template rule #removeall1dynamic] 
     */
	public void removeAllLowerboundinclusive() {
		Base.removeAll(this.model, this.getResource(), LOWERBOUNDINCLUSIVE);
	}
     /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@9d84476 has at least one value set 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return true if this property has at least one value
	 *
	 * [Generated from RDFReactor template rule #get0has-static] 
     */
	public static boolean hasUpperboundexclusive(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.has(model, instanceResource, UPPERBOUNDEXCLUSIVE);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@9d84476 has at least one value set 
     * @return true if this property has at least one value
	 *
	 * [Generated from RDFReactor template rule #get0has-dynamic] 
     */
	public boolean hasUpperboundexclusive() {
		return Base.has(this.model, this.getResource(), UPPERBOUNDEXCLUSIVE);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@9d84476 has the given value (maybe among other values).  
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be checked
     * @return true if this property contains (maybe among other) the given value
	 *
	 * [Generated from RDFReactor template rule #get0has-value-static] 
     */
	public static boolean hasUpperboundexclusive(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value ) {
		return Base.hasValue(model, instanceResource, UPPERBOUNDEXCLUSIVE);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@9d84476 has the given value (maybe among other values).  
	 * @param value the value to be checked
     * @return true if this property contains (maybe among other) the given value
	 *
	 * [Generated from RDFReactor template rule #get0has-value-dynamic] 
     */
	public boolean hasUpperboundexclusive( org.ontoware.rdf2go.model.node.Node value ) {
		return Base.hasValue(this.model, this.getResource(), UPPERBOUNDEXCLUSIVE);
	}

     /**
     * Get all values of property Upperboundexclusive as an Iterator over RDF2Go nodes 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ClosableIterator of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get7static] 
     */
	public static ClosableIterator<org.ontoware.rdf2go.model.node.Node> getAllUpperboundexclusive_asNode(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_asNode(model, instanceResource, UPPERBOUNDEXCLUSIVE);
	}
	
    /**
     * Get all values of property Upperboundexclusive as a ReactorResult of RDF2Go nodes 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a List of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get7static-reactor-result] 
     */
	public static ReactorResult<org.ontoware.rdf2go.model.node.Node> getAllUpperboundexclusive_asNode_(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_as(model, instanceResource, UPPERBOUNDEXCLUSIVE, org.ontoware.rdf2go.model.node.Node.class);
	}

    /**
     * Get all values of property Upperboundexclusive as an Iterator over RDF2Go nodes 
     * @return a ClosableIterator of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get8dynamic] 
     */
	public ClosableIterator<org.ontoware.rdf2go.model.node.Node> getAllUpperboundexclusive_asNode() {
		return Base.getAll_asNode(this.model, this.getResource(), UPPERBOUNDEXCLUSIVE);
	}

    /**
     * Get all values of property Upperboundexclusive as a ReactorResult of RDF2Go nodes 
     * @return a List of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get8dynamic-reactor-result] 
     */
	public ReactorResult<org.ontoware.rdf2go.model.node.Node> getAllUpperboundexclusive_asNode_() {
		return Base.getAll_as(this.model, this.getResource(), UPPERBOUNDEXCLUSIVE, org.ontoware.rdf2go.model.node.Node.class);
	}
     /**
     * Get all values of property Upperboundexclusive     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ClosableIterator of $type
	 *
	 * [Generated from RDFReactor template rule #get11static] 
     */
	public static ClosableIterator<Thing> getAllUpperboundexclusive(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll(model, instanceResource, UPPERBOUNDEXCLUSIVE, Thing.class);
	}
	
    /**
     * Get all values of property Upperboundexclusive as a ReactorResult of Thing 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ReactorResult of $type which can conveniently be converted to iterator, list or array
	 *
	 * [Generated from RDFReactor template rule #get11static-reactorresult] 
     */
	public static ReactorResult<Thing> getAllUpperboundexclusive_as(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_as(model, instanceResource, UPPERBOUNDEXCLUSIVE, Thing.class);
	}

    /**
     * Get all values of property Upperboundexclusive     * @return a ClosableIterator of $type
	 *
	 * [Generated from RDFReactor template rule #get12dynamic] 
     */
	public ClosableIterator<Thing> getAllUpperboundexclusive() {
		return Base.getAll(this.model, this.getResource(), UPPERBOUNDEXCLUSIVE, Thing.class);
	}

    /**
     * Get all values of property Upperboundexclusive as a ReactorResult of Thing 
     * @return a ReactorResult of $type which can conveniently be converted to iterator, list or array
	 *
	 * [Generated from RDFReactor template rule #get12dynamic-reactorresult] 
     */
	public ReactorResult<Thing> getAllUpperboundexclusive_as() {
		return Base.getAll_as(this.model, this.getResource(), UPPERBOUNDEXCLUSIVE, Thing.class);
	}
 
    /**
     * Adds a value to property Upperboundexclusive as an RDF2Go node 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #add1static] 
     */
	public static void addUpperboundexclusive( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.add(model, instanceResource, UPPERBOUNDEXCLUSIVE, value);
	}
	
    /**
     * Adds a value to property Upperboundexclusive as an RDF2Go node 
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #add1dynamic] 
     */
	public void addUpperboundexclusive( org.ontoware.rdf2go.model.node.Node value) {
		Base.add(this.model, this.getResource(), UPPERBOUNDEXCLUSIVE, value);
	}
    /**
     * Adds a value to property Upperboundexclusive from an instance of Thing 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #add3static] 
     */
	public static void addUpperboundexclusive(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, Thing value) {
		Base.add(model, instanceResource, UPPERBOUNDEXCLUSIVE, value);
	}
	
    /**
     * Adds a value to property Upperboundexclusive from an instance of Thing 
	 *
	 * [Generated from RDFReactor template rule #add4dynamic] 
     */
	public void addUpperboundexclusive(Thing value) {
		Base.add(this.model, this.getResource(), UPPERBOUNDEXCLUSIVE, value);
	}
  

    /**
     * Sets a value of property Upperboundexclusive from an RDF2Go node.
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be set
	 *
	 * [Generated from RDFReactor template rule #set1static] 
     */
	public static void setUpperboundexclusive( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.set(model, instanceResource, UPPERBOUNDEXCLUSIVE, value);
	}
	
    /**
     * Sets a value of property Upperboundexclusive from an RDF2Go node.
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set1dynamic] 
     */
	public void setUpperboundexclusive( org.ontoware.rdf2go.model.node.Node value) {
		Base.set(this.model, this.getResource(), UPPERBOUNDEXCLUSIVE, value);
	}
    /**
     * Sets a value of property Upperboundexclusive from an instance of Thing 
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set3static] 
     */
	public static void setUpperboundexclusive(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, Thing value) {
		Base.set(model, instanceResource, UPPERBOUNDEXCLUSIVE, value);
	}
	
    /**
     * Sets a value of property Upperboundexclusive from an instance of Thing 
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set4dynamic] 
     */
	public void setUpperboundexclusive(Thing value) {
		Base.set(this.model, this.getResource(), UPPERBOUNDEXCLUSIVE, value);
	}
  


    /**
     * Removes a value of property Upperboundexclusive as an RDF2Go node 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove1static] 
     */
	public static void removeUpperboundexclusive( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.remove(model, instanceResource, UPPERBOUNDEXCLUSIVE, value);
	}
	
    /**
     * Removes a value of property Upperboundexclusive as an RDF2Go node
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove1dynamic] 
     */
	public void removeUpperboundexclusive( org.ontoware.rdf2go.model.node.Node value) {
		Base.remove(this.model, this.getResource(), UPPERBOUNDEXCLUSIVE, value);
	}
    /**
     * Removes a value of property Upperboundexclusive given as an instance of Thing 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove3static] 
     */
	public static void removeUpperboundexclusive(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, Thing value) {
		Base.remove(model, instanceResource, UPPERBOUNDEXCLUSIVE, value);
	}
	
    /**
     * Removes a value of property Upperboundexclusive given as an instance of Thing 
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove4dynamic] 
     */
	public void removeUpperboundexclusive(Thing value) {
		Base.remove(this.model, this.getResource(), UPPERBOUNDEXCLUSIVE, value);
	}
  
    /**
     * Removes all values of property Upperboundexclusive     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #removeall1static] 
     */
	public static void removeAllUpperboundexclusive( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		Base.removeAll(model, instanceResource, UPPERBOUNDEXCLUSIVE);
	}
	
    /**
     * Removes all values of property Upperboundexclusive	 *
	 * [Generated from RDFReactor template rule #removeall1dynamic] 
     */
	public void removeAllUpperboundexclusive() {
		Base.removeAll(this.model, this.getResource(), UPPERBOUNDEXCLUSIVE);
	}
     /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@2770cd42 has at least one value set 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return true if this property has at least one value
	 *
	 * [Generated from RDFReactor template rule #get0has-static] 
     */
	public static boolean hasUpperboundinclusive(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.has(model, instanceResource, UPPERBOUNDINCLUSIVE);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@2770cd42 has at least one value set 
     * @return true if this property has at least one value
	 *
	 * [Generated from RDFReactor template rule #get0has-dynamic] 
     */
	public boolean hasUpperboundinclusive() {
		return Base.has(this.model, this.getResource(), UPPERBOUNDINCLUSIVE);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@2770cd42 has the given value (maybe among other values).  
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be checked
     * @return true if this property contains (maybe among other) the given value
	 *
	 * [Generated from RDFReactor template rule #get0has-value-static] 
     */
	public static boolean hasUpperboundinclusive(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value ) {
		return Base.hasValue(model, instanceResource, UPPERBOUNDINCLUSIVE);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@2770cd42 has the given value (maybe among other values).  
	 * @param value the value to be checked
     * @return true if this property contains (maybe among other) the given value
	 *
	 * [Generated from RDFReactor template rule #get0has-value-dynamic] 
     */
	public boolean hasUpperboundinclusive( org.ontoware.rdf2go.model.node.Node value ) {
		return Base.hasValue(this.model, this.getResource(), UPPERBOUNDINCLUSIVE);
	}

     /**
     * Get all values of property Upperboundinclusive as an Iterator over RDF2Go nodes 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ClosableIterator of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get7static] 
     */
	public static ClosableIterator<org.ontoware.rdf2go.model.node.Node> getAllUpperboundinclusive_asNode(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_asNode(model, instanceResource, UPPERBOUNDINCLUSIVE);
	}
	
    /**
     * Get all values of property Upperboundinclusive as a ReactorResult of RDF2Go nodes 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a List of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get7static-reactor-result] 
     */
	public static ReactorResult<org.ontoware.rdf2go.model.node.Node> getAllUpperboundinclusive_asNode_(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_as(model, instanceResource, UPPERBOUNDINCLUSIVE, org.ontoware.rdf2go.model.node.Node.class);
	}

    /**
     * Get all values of property Upperboundinclusive as an Iterator over RDF2Go nodes 
     * @return a ClosableIterator of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get8dynamic] 
     */
	public ClosableIterator<org.ontoware.rdf2go.model.node.Node> getAllUpperboundinclusive_asNode() {
		return Base.getAll_asNode(this.model, this.getResource(), UPPERBOUNDINCLUSIVE);
	}

    /**
     * Get all values of property Upperboundinclusive as a ReactorResult of RDF2Go nodes 
     * @return a List of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get8dynamic-reactor-result] 
     */
	public ReactorResult<org.ontoware.rdf2go.model.node.Node> getAllUpperboundinclusive_asNode_() {
		return Base.getAll_as(this.model, this.getResource(), UPPERBOUNDINCLUSIVE, org.ontoware.rdf2go.model.node.Node.class);
	}
     /**
     * Get all values of property Upperboundinclusive     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ClosableIterator of $type
	 *
	 * [Generated from RDFReactor template rule #get11static] 
     */
	public static ClosableIterator<Thing> getAllUpperboundinclusive(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll(model, instanceResource, UPPERBOUNDINCLUSIVE, Thing.class);
	}
	
    /**
     * Get all values of property Upperboundinclusive as a ReactorResult of Thing 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ReactorResult of $type which can conveniently be converted to iterator, list or array
	 *
	 * [Generated from RDFReactor template rule #get11static-reactorresult] 
     */
	public static ReactorResult<Thing> getAllUpperboundinclusive_as(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_as(model, instanceResource, UPPERBOUNDINCLUSIVE, Thing.class);
	}

    /**
     * Get all values of property Upperboundinclusive     * @return a ClosableIterator of $type
	 *
	 * [Generated from RDFReactor template rule #get12dynamic] 
     */
	public ClosableIterator<Thing> getAllUpperboundinclusive() {
		return Base.getAll(this.model, this.getResource(), UPPERBOUNDINCLUSIVE, Thing.class);
	}

    /**
     * Get all values of property Upperboundinclusive as a ReactorResult of Thing 
     * @return a ReactorResult of $type which can conveniently be converted to iterator, list or array
	 *
	 * [Generated from RDFReactor template rule #get12dynamic-reactorresult] 
     */
	public ReactorResult<Thing> getAllUpperboundinclusive_as() {
		return Base.getAll_as(this.model, this.getResource(), UPPERBOUNDINCLUSIVE, Thing.class);
	}
 
    /**
     * Adds a value to property Upperboundinclusive as an RDF2Go node 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #add1static] 
     */
	public static void addUpperboundinclusive( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.add(model, instanceResource, UPPERBOUNDINCLUSIVE, value);
	}
	
    /**
     * Adds a value to property Upperboundinclusive as an RDF2Go node 
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #add1dynamic] 
     */
	public void addUpperboundinclusive( org.ontoware.rdf2go.model.node.Node value) {
		Base.add(this.model, this.getResource(), UPPERBOUNDINCLUSIVE, value);
	}
    /**
     * Adds a value to property Upperboundinclusive from an instance of Thing 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #add3static] 
     */
	public static void addUpperboundinclusive(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, Thing value) {
		Base.add(model, instanceResource, UPPERBOUNDINCLUSIVE, value);
	}
	
    /**
     * Adds a value to property Upperboundinclusive from an instance of Thing 
	 *
	 * [Generated from RDFReactor template rule #add4dynamic] 
     */
	public void addUpperboundinclusive(Thing value) {
		Base.add(this.model, this.getResource(), UPPERBOUNDINCLUSIVE, value);
	}
  

    /**
     * Sets a value of property Upperboundinclusive from an RDF2Go node.
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be set
	 *
	 * [Generated from RDFReactor template rule #set1static] 
     */
	public static void setUpperboundinclusive( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.set(model, instanceResource, UPPERBOUNDINCLUSIVE, value);
	}
	
    /**
     * Sets a value of property Upperboundinclusive from an RDF2Go node.
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set1dynamic] 
     */
	public void setUpperboundinclusive( org.ontoware.rdf2go.model.node.Node value) {
		Base.set(this.model, this.getResource(), UPPERBOUNDINCLUSIVE, value);
	}
    /**
     * Sets a value of property Upperboundinclusive from an instance of Thing 
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set3static] 
     */
	public static void setUpperboundinclusive(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, Thing value) {
		Base.set(model, instanceResource, UPPERBOUNDINCLUSIVE, value);
	}
	
    /**
     * Sets a value of property Upperboundinclusive from an instance of Thing 
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set4dynamic] 
     */
	public void setUpperboundinclusive(Thing value) {
		Base.set(this.model, this.getResource(), UPPERBOUNDINCLUSIVE, value);
	}
  


    /**
     * Removes a value of property Upperboundinclusive as an RDF2Go node 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove1static] 
     */
	public static void removeUpperboundinclusive( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.remove(model, instanceResource, UPPERBOUNDINCLUSIVE, value);
	}
	
    /**
     * Removes a value of property Upperboundinclusive as an RDF2Go node
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove1dynamic] 
     */
	public void removeUpperboundinclusive( org.ontoware.rdf2go.model.node.Node value) {
		Base.remove(this.model, this.getResource(), UPPERBOUNDINCLUSIVE, value);
	}
    /**
     * Removes a value of property Upperboundinclusive given as an instance of Thing 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove3static] 
     */
	public static void removeUpperboundinclusive(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, Thing value) {
		Base.remove(model, instanceResource, UPPERBOUNDINCLUSIVE, value);
	}
	
    /**
     * Removes a value of property Upperboundinclusive given as an instance of Thing 
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove4dynamic] 
     */
	public void removeUpperboundinclusive(Thing value) {
		Base.remove(this.model, this.getResource(), UPPERBOUNDINCLUSIVE, value);
	}
  
    /**
     * Removes all values of property Upperboundinclusive     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #removeall1static] 
     */
	public static void removeAllUpperboundinclusive( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		Base.removeAll(model, instanceResource, UPPERBOUNDINCLUSIVE);
	}
	
    /**
     * Removes all values of property Upperboundinclusive	 *
	 * [Generated from RDFReactor template rule #removeall1dynamic] 
     */
	public void removeAllUpperboundinclusive() {
		Base.removeAll(this.model, this.getResource(), UPPERBOUNDINCLUSIVE);
	}
 }