/**
 * generated by http://RDFReactor.semweb4j.org ($Id: CodeGenerator.java 1535 2008-09-09 15:44:46Z max.at.xam.de $) on 29.10.13 09:05
 */
package org.purl.rvl.interpreter.rvl;

import org.ontoware.aifbcommons.collection.ClosableIterator;
import org.ontoware.rdf2go.exception.ModelRuntimeException;
import org.ontoware.rdf2go.model.Model;
import org.ontoware.rdf2go.model.node.BlankNode;
import org.ontoware.rdf2go.model.node.URI;
import org.ontoware.rdf2go.model.node.impl.URIImpl;
import org.ontoware.rdfreactor.runtime.Base;
import org.ontoware.rdfreactor.runtime.ReactorResult;

/**
 * This class manages access to these properties:
 * <ul>
 *   <li> Fallsbackto </li>
 *   <li> Includeinlegend </li>
 * </ul>
 *
 * This class was generated by <a href="http://RDFReactor.semweb4j.org">RDFReactor</a> on 29.10.13 09:05
 */
public class Mapping extends Thing {

    /** http://purl.org/rvl/Mapping */
    @SuppressWarnings("hiding")
	public static final URI RDFS_CLASS = new URIImpl("http://purl.org/rvl/Mapping", false);

    /** http://purl.org/rvl/fallsBackTo */
    @SuppressWarnings("hiding")
	public static final URI FALLSBACKTO = new URIImpl("http://purl.org/rvl/fallsBackTo",false);

    /** http://purl.org/rvl/includeInLegend */
    @SuppressWarnings("hiding")
	public static final URI INCLUDEINLEGEND = new URIImpl("http://purl.org/rvl/includeInLegend",false);

    /** 
     * All property-URIs with this class as domain.
     * All properties of all super-classes are also available. 
     */
    @SuppressWarnings("hiding")
    public static final URI[] MANAGED_URIS = {
      new URIImpl("http://purl.org/rvl/fallsBackTo",false),
      new URIImpl("http://purl.org/rvl/includeInLegend",false) 
    };


	// protected constructors needed for inheritance
	
	/**
	 * Returns a Java wrapper over an RDF object, identified by URI.
	 * Creating two wrappers for the same instanceURI is legal.
	 * @param model RDF2GO Model implementation, see http://rdf2go.semweb4j.org
	 * @param classURI URI of RDFS class
	 * @param instanceIdentifier Resource that identifies this instance
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 *
	 * [Generated from RDFReactor template rule #c1] 
	 */
	protected Mapping ( Model model, URI classURI, org.ontoware.rdf2go.model.node.Resource instanceIdentifier, boolean write ) {
		super(model, classURI, instanceIdentifier, write);
	}

	// public constructors

	/**
	 * Returns a Java wrapper over an RDF object, identified by URI.
	 * Creating two wrappers for the same instanceURI is legal.
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param instanceIdentifier an RDF2Go Resource identifying this instance
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 *
	 * [Generated from RDFReactor template rule #c2] 
	 */
	public Mapping ( Model model, org.ontoware.rdf2go.model.node.Resource instanceIdentifier, boolean write ) {
		super(model, RDFS_CLASS, instanceIdentifier, write);
	}


	/**
	 * Returns a Java wrapper over an RDF object, identified by a URI, given as a String.
	 * Creating two wrappers for the same URI is legal.
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param uriString a URI given as a String
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 * @throws ModelRuntimeException if URI syntax is wrong
	 *
	 * [Generated from RDFReactor template rule #c7] 
	 */
	public Mapping ( Model model, String uriString, boolean write) throws ModelRuntimeException {
		super(model, RDFS_CLASS, new URIImpl(uriString,false), write);
	}

	/**
	 * Returns a Java wrapper over an RDF object, identified by a blank node.
	 * Creating two wrappers for the same blank node is legal.
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param bnode BlankNode of this instance
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 *
	 * [Generated from RDFReactor template rule #c8] 
	 */
	public Mapping ( Model model, BlankNode bnode, boolean write ) {
		super(model, RDFS_CLASS, bnode, write);
	}

	/**
	 * Returns a Java wrapper over an RDF object, identified by 
	 * a randomly generated URI.
	 * Creating two wrappers results in different URIs.
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 *
	 * [Generated from RDFReactor template rule #c9] 
	 */
	public Mapping ( Model model, boolean write ) {
		super(model, RDFS_CLASS, model.newRandomUniqueURI(), write);
	}

    ///////////////////////////////////////////////////////////////////
    // typing

	/**
	 * Return an existing instance of this class in the model. No statements are written.
	 * @param model an RDF2Go model
	 * @param instanceResource an RDF2Go resource
	 * @return an instance of Mapping  or null if none existst
	 *
	 * [Generated from RDFReactor template rule #class0] 
	 */
	public static Mapping  getInstance(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getInstance(model, instanceResource, Mapping.class);
	}

	/**
	 * Create a new instance of this class in the model. 
	 * That is, create the statement (instanceResource, RDF.type, http://purl.org/rvl/Mapping).
	 * @param model an RDF2Go model
	 * @param instanceResource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #class1] 
	 */
	public static void createInstance(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		Base.createInstance(model, RDFS_CLASS, instanceResource);
	}

	/**
	 * @param model an RDF2Go model
	 * @param instanceResource an RDF2Go resource
	 * @return true if instanceResource is an instance of this class in the model
	 *
	 * [Generated from RDFReactor template rule #class2] 
	 */
	public static boolean hasInstance(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.hasInstance(model, RDFS_CLASS, instanceResource);
	}

	/**
	 * @param model an RDF2Go model
	 * @return all instances of this class in Model 'model' as RDF resources
	 *
	 * [Generated from RDFReactor template rule #class3] 
	 */
	public static ClosableIterator<org.ontoware.rdf2go.model.node.Resource> getAllInstances(Model model) {
		return Base.getAllInstances(model, RDFS_CLASS, org.ontoware.rdf2go.model.node.Resource.class);
	}

	/**
	 * @param model an RDF2Go model
	 * @return all instances of this class in Model 'model' as a ReactorResult,
	 * which can conveniently be converted to iterator, list or array.
	 *
	 * [Generated from RDFReactor template rule #class3-as] 
	 */
	public static ReactorResult<? extends Mapping> getAllInstances_as(Model model) {
		return Base.getAllInstances_as(model, RDFS_CLASS, Mapping.class );
	}

    /**
	 * Remove rdf:type Mapping from this instance. Other triples are not affected.
	 * To delete more, use deleteAllProperties
	 * @param model an RDF2Go model
	 * @param instanceResource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #class4] 
	 */
	public static void deleteInstance(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		Base.deleteInstance(model, RDFS_CLASS, instanceResource);
	}

	/**
	 * Delete all (this, *, *), i.e. including rdf:type
	 * @param model an RDF2Go model
	 * @param resource
	 */
	public static void deleteAllProperties(Model model,	org.ontoware.rdf2go.model.node.Resource instanceResource) {
		Base.deleteAllProperties(model, instanceResource);
	}

    ///////////////////////////////////////////////////////////////////
    // property access methods

	/**
	 * @param model an RDF2Go model
	 * @param objectValue
	 * @return all A's as RDF resources, that have a relation 'Sub_mapping' to this Mapping instance
	 *
	 * [Generated from RDFReactor template rule #getallinverse1static] 
	 */
	public static ClosableIterator<org.ontoware.rdf2go.model.node.Resource> getAllSub_mapping_Inverse( Model model, Object objectValue) {
		return Base.getAll_Inverse(model, Sub_mappingrelation.SUB_MAPPING, objectValue);
	}

	/**
	 * @return all A's as RDF resources, that have a relation 'Sub_mapping' to this Mapping instance
	 *
	 * [Generated from RDFReactor template rule #getallinverse1dynamic] 
	 */
	public ClosableIterator<org.ontoware.rdf2go.model.node.Resource> getAllSub_mapping_Inverse() {
		return Base.getAll_Inverse(this.model, Sub_mappingrelation.SUB_MAPPING, this.getResource() );
	}

	/**
	 * @param model an RDF2Go model
	 * @param objectValue
	 * @return all A's as a ReactorResult, that have a relation 'Sub_mapping' to this Mapping instance
	 *
	 * [Generated from RDFReactor template rule #getallinverse-as1static] 
	 */
	public static ReactorResult<org.ontoware.rdf2go.model.node.Resource> getAllSub_mapping_Inverse_as( Model model, Object objectValue) {
		return Base.getAll_Inverse_as(model, Sub_mappingrelation.SUB_MAPPING, objectValue, org.ontoware.rdf2go.model.node.Resource.class);
	}


	/**
	 * @param model an RDF2Go model
	 * @param objectValue
	 * @return all A's as RDF resources, that have a relation 'Fallsbackto' to this Mapping instance
	 *
	 * [Generated from RDFReactor template rule #getallinverse1static] 
	 */
	public static ClosableIterator<org.ontoware.rdf2go.model.node.Resource> getAllFallsbackto_Inverse( Model model, Object objectValue) {
		return Base.getAll_Inverse(model, Mapping.FALLSBACKTO, objectValue);
	}

	/**
	 * @return all A's as RDF resources, that have a relation 'Fallsbackto' to this Mapping instance
	 *
	 * [Generated from RDFReactor template rule #getallinverse1dynamic] 
	 */
	public ClosableIterator<org.ontoware.rdf2go.model.node.Resource> getAllFallsbackto_Inverse() {
		return Base.getAll_Inverse(this.model, Mapping.FALLSBACKTO, this.getResource() );
	}

	/**
	 * @param model an RDF2Go model
	 * @param objectValue
	 * @return all A's as a ReactorResult, that have a relation 'Fallsbackto' to this Mapping instance
	 *
	 * [Generated from RDFReactor template rule #getallinverse-as1static] 
	 */
	public static ReactorResult<org.ontoware.rdf2go.model.node.Resource> getAllFallsbackto_Inverse_as( Model model, Object objectValue) {
		return Base.getAll_Inverse_as(model, Mapping.FALLSBACKTO, objectValue, org.ontoware.rdf2go.model.node.Resource.class);
	}



    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@4e72aa81 has at least one value set 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return true if this property has at least one value
	 *
	 * [Generated from RDFReactor template rule #get0has-static] 
     */
	public static boolean hasFallsbackto(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.has(model, instanceResource, FALLSBACKTO);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@4e72aa81 has at least one value set 
     * @return true if this property has at least one value
	 *
	 * [Generated from RDFReactor template rule #get0has-dynamic] 
     */
	public boolean hasFallsbackto() {
		return Base.has(this.model, this.getResource(), FALLSBACKTO);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@4e72aa81 has the given value (maybe among other values).  
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be checked
     * @return true if this property contains (maybe among other) the given value
	 *
	 * [Generated from RDFReactor template rule #get0has-value-static] 
     */
	public static boolean hasFallsbackto(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value ) {
		return Base.hasValue(model, instanceResource, FALLSBACKTO);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@4e72aa81 has the given value (maybe among other values).  
	 * @param value the value to be checked
     * @return true if this property contains (maybe among other) the given value
	 *
	 * [Generated from RDFReactor template rule #get0has-value-dynamic] 
     */
	public boolean hasFallsbackto( org.ontoware.rdf2go.model.node.Node value ) {
		return Base.hasValue(this.model, this.getResource(), FALLSBACKTO);
	}

     /**
     * Get all values of property Fallsbackto as an Iterator over RDF2Go nodes 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ClosableIterator of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get7static] 
     */
	public static ClosableIterator<org.ontoware.rdf2go.model.node.Node> getAllFallsbackto_asNode(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_asNode(model, instanceResource, FALLSBACKTO);
	}
	
    /**
     * Get all values of property Fallsbackto as a ReactorResult of RDF2Go nodes 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a List of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get7static-reactor-result] 
     */
	public static ReactorResult<org.ontoware.rdf2go.model.node.Node> getAllFallsbackto_asNode_(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_as(model, instanceResource, FALLSBACKTO, org.ontoware.rdf2go.model.node.Node.class);
	}

    /**
     * Get all values of property Fallsbackto as an Iterator over RDF2Go nodes 
     * @return a ClosableIterator of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get8dynamic] 
     */
	public ClosableIterator<org.ontoware.rdf2go.model.node.Node> getAllFallsbackto_asNode() {
		return Base.getAll_asNode(this.model, this.getResource(), FALLSBACKTO);
	}

    /**
     * Get all values of property Fallsbackto as a ReactorResult of RDF2Go nodes 
     * @return a List of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get8dynamic-reactor-result] 
     */
	public ReactorResult<org.ontoware.rdf2go.model.node.Node> getAllFallsbackto_asNode_() {
		return Base.getAll_as(this.model, this.getResource(), FALLSBACKTO, org.ontoware.rdf2go.model.node.Node.class);
	}
     /**
     * Get all values of property Fallsbackto     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ClosableIterator of $type
	 *
	 * [Generated from RDFReactor template rule #get11static] 
     */
	public static ClosableIterator<Mapping> getAllFallsbackto(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll(model, instanceResource, FALLSBACKTO, Mapping.class);
	}
	
    /**
     * Get all values of property Fallsbackto as a ReactorResult of Mapping 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ReactorResult of $type which can conveniently be converted to iterator, list or array
	 *
	 * [Generated from RDFReactor template rule #get11static-reactorresult] 
     */
	public static ReactorResult<Mapping> getAllFallsbackto_as(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_as(model, instanceResource, FALLSBACKTO, Mapping.class);
	}

    /**
     * Get all values of property Fallsbackto     * @return a ClosableIterator of $type
	 *
	 * [Generated from RDFReactor template rule #get12dynamic] 
     */
	public ClosableIterator<Mapping> getAllFallsbackto() {
		return Base.getAll(this.model, this.getResource(), FALLSBACKTO, Mapping.class);
	}

    /**
     * Get all values of property Fallsbackto as a ReactorResult of Mapping 
     * @return a ReactorResult of $type which can conveniently be converted to iterator, list or array
	 *
	 * [Generated from RDFReactor template rule #get12dynamic-reactorresult] 
     */
	public ReactorResult<Mapping> getAllFallsbackto_as() {
		return Base.getAll_as(this.model, this.getResource(), FALLSBACKTO, Mapping.class);
	}
 
    /**
     * Adds a value to property Fallsbackto as an RDF2Go node 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #add1static] 
     */
	public static void addFallsbackto( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.add(model, instanceResource, FALLSBACKTO, value);
	}
	
    /**
     * Adds a value to property Fallsbackto as an RDF2Go node 
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #add1dynamic] 
     */
	public void addFallsbackto( org.ontoware.rdf2go.model.node.Node value) {
		Base.add(this.model, this.getResource(), FALLSBACKTO, value);
	}
    /**
     * Adds a value to property Fallsbackto from an instance of Mapping 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #add3static] 
     */
	public static void addFallsbackto(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, Mapping value) {
		Base.add(model, instanceResource, FALLSBACKTO, value);
	}
	
    /**
     * Adds a value to property Fallsbackto from an instance of Mapping 
	 *
	 * [Generated from RDFReactor template rule #add4dynamic] 
     */
	public void addFallsbackto(Mapping value) {
		Base.add(this.model, this.getResource(), FALLSBACKTO, value);
	}
  

    /**
     * Sets a value of property Fallsbackto from an RDF2Go node.
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be set
	 *
	 * [Generated from RDFReactor template rule #set1static] 
     */
	public static void setFallsbackto( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.set(model, instanceResource, FALLSBACKTO, value);
	}
	
    /**
     * Sets a value of property Fallsbackto from an RDF2Go node.
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set1dynamic] 
     */
	public void setFallsbackto( org.ontoware.rdf2go.model.node.Node value) {
		Base.set(this.model, this.getResource(), FALLSBACKTO, value);
	}
    /**
     * Sets a value of property Fallsbackto from an instance of Mapping 
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set3static] 
     */
	public static void setFallsbackto(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, Mapping value) {
		Base.set(model, instanceResource, FALLSBACKTO, value);
	}
	
    /**
     * Sets a value of property Fallsbackto from an instance of Mapping 
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set4dynamic] 
     */
	public void setFallsbackto(Mapping value) {
		Base.set(this.model, this.getResource(), FALLSBACKTO, value);
	}
  


    /**
     * Removes a value of property Fallsbackto as an RDF2Go node 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove1static] 
     */
	public static void removeFallsbackto( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.remove(model, instanceResource, FALLSBACKTO, value);
	}
	
    /**
     * Removes a value of property Fallsbackto as an RDF2Go node
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove1dynamic] 
     */
	public void removeFallsbackto( org.ontoware.rdf2go.model.node.Node value) {
		Base.remove(this.model, this.getResource(), FALLSBACKTO, value);
	}
    /**
     * Removes a value of property Fallsbackto given as an instance of Mapping 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove3static] 
     */
	public static void removeFallsbackto(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, Mapping value) {
		Base.remove(model, instanceResource, FALLSBACKTO, value);
	}
	
    /**
     * Removes a value of property Fallsbackto given as an instance of Mapping 
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove4dynamic] 
     */
	public void removeFallsbackto(Mapping value) {
		Base.remove(this.model, this.getResource(), FALLSBACKTO, value);
	}
  
    /**
     * Removes all values of property Fallsbackto     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #removeall1static] 
     */
	public static void removeAllFallsbackto( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		Base.removeAll(model, instanceResource, FALLSBACKTO);
	}
	
    /**
     * Removes all values of property Fallsbackto	 *
	 * [Generated from RDFReactor template rule #removeall1dynamic] 
     */
	public void removeAllFallsbackto() {
		Base.removeAll(this.model, this.getResource(), FALLSBACKTO);
	}
     /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@279d45d6 has at least one value set 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return true if this property has at least one value
	 *
	 * [Generated from RDFReactor template rule #get0has-static] 
     */
	public static boolean hasIncludeinlegend(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.has(model, instanceResource, INCLUDEINLEGEND);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@279d45d6 has at least one value set 
     * @return true if this property has at least one value
	 *
	 * [Generated from RDFReactor template rule #get0has-dynamic] 
     */
	public boolean hasIncludeinlegend() {
		return Base.has(this.model, this.getResource(), INCLUDEINLEGEND);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@279d45d6 has the given value (maybe among other values).  
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be checked
     * @return true if this property contains (maybe among other) the given value
	 *
	 * [Generated from RDFReactor template rule #get0has-value-static] 
     */
	public static boolean hasIncludeinlegend(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value ) {
		return Base.hasValue(model, instanceResource, INCLUDEINLEGEND);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@279d45d6 has the given value (maybe among other values).  
	 * @param value the value to be checked
     * @return true if this property contains (maybe among other) the given value
	 *
	 * [Generated from RDFReactor template rule #get0has-value-dynamic] 
     */
	public boolean hasIncludeinlegend( org.ontoware.rdf2go.model.node.Node value ) {
		return Base.hasValue(this.model, this.getResource(), INCLUDEINLEGEND);
	}

     /**
     * Get all values of property Includeinlegend as an Iterator over RDF2Go nodes 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ClosableIterator of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get7static] 
     */
	public static ClosableIterator<org.ontoware.rdf2go.model.node.Node> getAllIncludeinlegend_asNode(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_asNode(model, instanceResource, INCLUDEINLEGEND);
	}
	
    /**
     * Get all values of property Includeinlegend as a ReactorResult of RDF2Go nodes 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a List of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get7static-reactor-result] 
     */
	public static ReactorResult<org.ontoware.rdf2go.model.node.Node> getAllIncludeinlegend_asNode_(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_as(model, instanceResource, INCLUDEINLEGEND, org.ontoware.rdf2go.model.node.Node.class);
	}

    /**
     * Get all values of property Includeinlegend as an Iterator over RDF2Go nodes 
     * @return a ClosableIterator of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get8dynamic] 
     */
	public ClosableIterator<org.ontoware.rdf2go.model.node.Node> getAllIncludeinlegend_asNode() {
		return Base.getAll_asNode(this.model, this.getResource(), INCLUDEINLEGEND);
	}

    /**
     * Get all values of property Includeinlegend as a ReactorResult of RDF2Go nodes 
     * @return a List of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get8dynamic-reactor-result] 
     */
	public ReactorResult<org.ontoware.rdf2go.model.node.Node> getAllIncludeinlegend_asNode_() {
		return Base.getAll_as(this.model, this.getResource(), INCLUDEINLEGEND, org.ontoware.rdf2go.model.node.Node.class);
	}
     /**
     * Get all values of property Includeinlegend     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ClosableIterator of $type
	 *
	 * [Generated from RDFReactor template rule #get11static] 
     */
	public static ClosableIterator<java.lang.Boolean> getAllIncludeinlegend(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll(model, instanceResource, INCLUDEINLEGEND, java.lang.Boolean.class);
	}
	
    /**
     * Get all values of property Includeinlegend as a ReactorResult of java.lang.Boolean 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ReactorResult of $type which can conveniently be converted to iterator, list or array
	 *
	 * [Generated from RDFReactor template rule #get11static-reactorresult] 
     */
	public static ReactorResult<java.lang.Boolean> getAllIncludeinlegend_as(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_as(model, instanceResource, INCLUDEINLEGEND, java.lang.Boolean.class);
	}

    /**
     * Get all values of property Includeinlegend     * @return a ClosableIterator of $type
	 *
	 * [Generated from RDFReactor template rule #get12dynamic] 
     */
	public ClosableIterator<java.lang.Boolean> getAllIncludeinlegend() {
		return Base.getAll(this.model, this.getResource(), INCLUDEINLEGEND, java.lang.Boolean.class);
	}

    /**
     * Get all values of property Includeinlegend as a ReactorResult of java.lang.Boolean 
     * @return a ReactorResult of $type which can conveniently be converted to iterator, list or array
	 *
	 * [Generated from RDFReactor template rule #get12dynamic-reactorresult] 
     */
	public ReactorResult<java.lang.Boolean> getAllIncludeinlegend_as() {
		return Base.getAll_as(this.model, this.getResource(), INCLUDEINLEGEND, java.lang.Boolean.class);
	}
 
    /**
     * Adds a value to property Includeinlegend as an RDF2Go node 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #add1static] 
     */
	public static void addIncludeinlegend( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.add(model, instanceResource, INCLUDEINLEGEND, value);
	}
	
    /**
     * Adds a value to property Includeinlegend as an RDF2Go node 
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #add1dynamic] 
     */
	public void addIncludeinlegend( org.ontoware.rdf2go.model.node.Node value) {
		Base.add(this.model, this.getResource(), INCLUDEINLEGEND, value);
	}
    /**
     * Adds a value to property Includeinlegend from an instance of java.lang.Boolean 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #add3static] 
     */
	public static void addIncludeinlegend(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, java.lang.Boolean value) {
		Base.add(model, instanceResource, INCLUDEINLEGEND, value);
	}
	
    /**
     * Adds a value to property Includeinlegend from an instance of java.lang.Boolean 
	 *
	 * [Generated from RDFReactor template rule #add4dynamic] 
     */
	public void addIncludeinlegend(java.lang.Boolean value) {
		Base.add(this.model, this.getResource(), INCLUDEINLEGEND, value);
	}
  

    /**
     * Sets a value of property Includeinlegend from an RDF2Go node.
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be set
	 *
	 * [Generated from RDFReactor template rule #set1static] 
     */
	public static void setIncludeinlegend( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.set(model, instanceResource, INCLUDEINLEGEND, value);
	}
	
    /**
     * Sets a value of property Includeinlegend from an RDF2Go node.
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set1dynamic] 
     */
	public void setIncludeinlegend( org.ontoware.rdf2go.model.node.Node value) {
		Base.set(this.model, this.getResource(), INCLUDEINLEGEND, value);
	}
    /**
     * Sets a value of property Includeinlegend from an instance of java.lang.Boolean 
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set3static] 
     */
	public static void setIncludeinlegend(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, java.lang.Boolean value) {
		Base.set(model, instanceResource, INCLUDEINLEGEND, value);
	}
	
    /**
     * Sets a value of property Includeinlegend from an instance of java.lang.Boolean 
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set4dynamic] 
     */
	public void setIncludeinlegend(java.lang.Boolean value) {
		Base.set(this.model, this.getResource(), INCLUDEINLEGEND, value);
	}
  


    /**
     * Removes a value of property Includeinlegend as an RDF2Go node 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove1static] 
     */
	public static void removeIncludeinlegend( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.remove(model, instanceResource, INCLUDEINLEGEND, value);
	}
	
    /**
     * Removes a value of property Includeinlegend as an RDF2Go node
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove1dynamic] 
     */
	public void removeIncludeinlegend( org.ontoware.rdf2go.model.node.Node value) {
		Base.remove(this.model, this.getResource(), INCLUDEINLEGEND, value);
	}
    /**
     * Removes a value of property Includeinlegend given as an instance of java.lang.Boolean 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove3static] 
     */
	public static void removeIncludeinlegend(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, java.lang.Boolean value) {
		Base.remove(model, instanceResource, INCLUDEINLEGEND, value);
	}
	
    /**
     * Removes a value of property Includeinlegend given as an instance of java.lang.Boolean 
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove4dynamic] 
     */
	public void removeIncludeinlegend(java.lang.Boolean value) {
		Base.remove(this.model, this.getResource(), INCLUDEINLEGEND, value);
	}
  
    /**
     * Removes all values of property Includeinlegend     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #removeall1static] 
     */
	public static void removeAllIncludeinlegend( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		Base.removeAll(model, instanceResource, INCLUDEINLEGEND);
	}
	
    /**
     * Removes all values of property Includeinlegend	 *
	 * [Generated from RDFReactor template rule #removeall1dynamic] 
     */
	public void removeAllIncludeinlegend() {
		Base.removeAll(this.model, this.getResource(), INCLUDEINLEGEND);
	}
 }