/**
 * generated by http://RDFReactor.semweb4j.org ($Id: CodeGenerator.java 1535 2008-09-09 15:44:46Z max.at.xam.de $) on 29.10.13 09:05
 */
package org.purl.rvl.interpreter.rvl;

import org.ontoware.aifbcommons.collection.ClosableIterator;
import org.ontoware.rdf2go.exception.ModelRuntimeException;
import org.ontoware.rdf2go.model.Model;
import org.ontoware.rdf2go.model.node.BlankNode;
import org.ontoware.rdf2go.model.node.URI;
import org.ontoware.rdf2go.model.node.impl.URIImpl;
import org.ontoware.rdfreactor.runtime.Base;
import org.ontoware.rdfreactor.runtime.ReactorResult;

/**
 * This class manages access to these properties:
 * <ul>
 *   <li> Onrole </li>
 *   <li> Ontriplepart </li>
 *   <li> Sub_mapping </li>
 * </ul>
 *
 * This class was generated by <a href="http://RDFReactor.semweb4j.org">RDFReactor</a> on 29.10.13 09:05
 */
public class Sub_mappingrelation extends N_aryrelation {

    /** http://purl.org/rvl/SubMappingRelation */
    @SuppressWarnings("hiding")
	public static final URI RDFS_CLASS = new URIImpl("http://purl.org/rvl/SubMappingRelation", false);

    /** http://purl.org/rvl/subMapping_onRole */
    @SuppressWarnings("hiding")
	public static final URI ONROLE = new URIImpl("http://purl.org/rvl/subMapping_onRole",false);

    /** http://purl.org/rvl/subMapping_onTriplePart */
    @SuppressWarnings("hiding")
	public static final URI ONTRIPLEPART = new URIImpl("http://purl.org/rvl/subMapping_onTriplePart",false);

    /** http://purl.org/rvl/subMapping_mapping */
    @SuppressWarnings("hiding")
	public static final URI SUB_MAPPING = new URIImpl("http://purl.org/rvl/subMapping_mapping",false);

    /** 
     * All property-URIs with this class as domain.
     * All properties of all super-classes are also available. 
     */
    @SuppressWarnings("hiding")
    public static final URI[] MANAGED_URIS = {
      new URIImpl("http://purl.org/rvl/subMapping_onRole",false),
      new URIImpl("http://purl.org/rvl/subMapping_onTriplePart",false),
      new URIImpl("http://purl.org/rvl/subMapping_mapping",false) 
    };


	// protected constructors needed for inheritance
	
	/**
	 * Returns a Java wrapper over an RDF object, identified by URI.
	 * Creating two wrappers for the same instanceURI is legal.
	 * @param model RDF2GO Model implementation, see http://rdf2go.semweb4j.org
	 * @param classURI URI of RDFS class
	 * @param instanceIdentifier Resource that identifies this instance
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 *
	 * [Generated from RDFReactor template rule #c1] 
	 */
	protected Sub_mappingrelation ( Model model, URI classURI, org.ontoware.rdf2go.model.node.Resource instanceIdentifier, boolean write ) {
		super(model, classURI, instanceIdentifier, write);
	}

	// public constructors

	/**
	 * Returns a Java wrapper over an RDF object, identified by URI.
	 * Creating two wrappers for the same instanceURI is legal.
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param instanceIdentifier an RDF2Go Resource identifying this instance
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 *
	 * [Generated from RDFReactor template rule #c2] 
	 */
	public Sub_mappingrelation ( Model model, org.ontoware.rdf2go.model.node.Resource instanceIdentifier, boolean write ) {
		super(model, RDFS_CLASS, instanceIdentifier, write);
	}


	/**
	 * Returns a Java wrapper over an RDF object, identified by a URI, given as a String.
	 * Creating two wrappers for the same URI is legal.
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param uriString a URI given as a String
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 * @throws ModelRuntimeException if URI syntax is wrong
	 *
	 * [Generated from RDFReactor template rule #c7] 
	 */
	public Sub_mappingrelation ( Model model, String uriString, boolean write) throws ModelRuntimeException {
		super(model, RDFS_CLASS, new URIImpl(uriString,false), write);
	}

	/**
	 * Returns a Java wrapper over an RDF object, identified by a blank node.
	 * Creating two wrappers for the same blank node is legal.
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param bnode BlankNode of this instance
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 *
	 * [Generated from RDFReactor template rule #c8] 
	 */
	public Sub_mappingrelation ( Model model, BlankNode bnode, boolean write ) {
		super(model, RDFS_CLASS, bnode, write);
	}

	/**
	 * Returns a Java wrapper over an RDF object, identified by 
	 * a randomly generated URI.
	 * Creating two wrappers results in different URIs.
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 *
	 * [Generated from RDFReactor template rule #c9] 
	 */
	public Sub_mappingrelation ( Model model, boolean write ) {
		super(model, RDFS_CLASS, model.newRandomUniqueURI(), write);
	}

    ///////////////////////////////////////////////////////////////////
    // typing

	/**
	 * Return an existing instance of this class in the model. No statements are written.
	 * @param model an RDF2Go model
	 * @param instanceResource an RDF2Go resource
	 * @return an instance of Sub_mappingrelation  or null if none existst
	 *
	 * [Generated from RDFReactor template rule #class0] 
	 */
	public static Sub_mappingrelation  getInstance(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getInstance(model, instanceResource, Sub_mappingrelation.class);
	}

	/**
	 * Create a new instance of this class in the model. 
	 * That is, create the statement (instanceResource, RDF.type, http://purl.org/rvl/SubMappingRelation).
	 * @param model an RDF2Go model
	 * @param instanceResource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #class1] 
	 */
	public static void createInstance(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		Base.createInstance(model, RDFS_CLASS, instanceResource);
	}

	/**
	 * @param model an RDF2Go model
	 * @param instanceResource an RDF2Go resource
	 * @return true if instanceResource is an instance of this class in the model
	 *
	 * [Generated from RDFReactor template rule #class2] 
	 */
	public static boolean hasInstance(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.hasInstance(model, RDFS_CLASS, instanceResource);
	}

	/**
	 * @param model an RDF2Go model
	 * @return all instances of this class in Model 'model' as RDF resources
	 *
	 * [Generated from RDFReactor template rule #class3] 
	 */
	public static ClosableIterator<org.ontoware.rdf2go.model.node.Resource> getAllInstances(Model model) {
		return Base.getAllInstances(model, RDFS_CLASS, org.ontoware.rdf2go.model.node.Resource.class);
	}

	/**
	 * @param model an RDF2Go model
	 * @return all instances of this class in Model 'model' as a ReactorResult,
	 * which can conveniently be converted to iterator, list or array.
	 *
	 * [Generated from RDFReactor template rule #class3-as] 
	 */
	public static ReactorResult<? extends Sub_mappingrelation> getAllInstances_as(Model model) {
		return Base.getAllInstances_as(model, RDFS_CLASS, Sub_mappingrelation.class );
	}

    /**
	 * Remove rdf:type Sub_mappingrelation from this instance. Other triples are not affected.
	 * To delete more, use deleteAllProperties
	 * @param model an RDF2Go model
	 * @param instanceResource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #class4] 
	 */
	public static void deleteInstance(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		Base.deleteInstance(model, RDFS_CLASS, instanceResource);
	}

	/**
	 * Delete all (this, *, *), i.e. including rdf:type
	 * @param model an RDF2Go model
	 * @param resource
	 */
	public static void deleteAllProperties(Model model,	org.ontoware.rdf2go.model.node.Resource instanceResource) {
		Base.deleteAllProperties(model, instanceResource);
	}

    ///////////////////////////////////////////////////////////////////
    // property access methods

	/**
	 * @param model an RDF2Go model
	 * @param objectValue
	 * @return all A's as RDF resources, that have a relation 'Sub_mapping' to this Sub_mappingrelation instance
	 *
	 * [Generated from RDFReactor template rule #getallinverse1static] 
	 */
	public static ClosableIterator<org.ontoware.rdf2go.model.node.Resource> getAllSub_mapping_Inverse( Model model, Object objectValue) {
		return Base.getAll_Inverse(model, PropertyMapping.SUB_MAPPING, objectValue);
	}

	/**
	 * @return all A's as RDF resources, that have a relation 'Sub_mapping' to this Sub_mappingrelation instance
	 *
	 * [Generated from RDFReactor template rule #getallinverse1dynamic] 
	 */
	public ClosableIterator<org.ontoware.rdf2go.model.node.Resource> getAllSub_mapping_Inverse() {
		return Base.getAll_Inverse(this.model, PropertyMapping.SUB_MAPPING, this.getResource() );
	}

	/**
	 * @param model an RDF2Go model
	 * @param objectValue
	 * @return all A's as a ReactorResult, that have a relation 'Sub_mapping' to this Sub_mappingrelation instance
	 *
	 * [Generated from RDFReactor template rule #getallinverse-as1static] 
	 */
	public static ReactorResult<org.ontoware.rdf2go.model.node.Resource> getAllSub_mapping_Inverse_as( Model model, Object objectValue) {
		return Base.getAll_Inverse_as(model, PropertyMapping.SUB_MAPPING, objectValue, org.ontoware.rdf2go.model.node.Resource.class);
	}



    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@52d92404 has at least one value set 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return true if this property has at least one value
	 *
	 * [Generated from RDFReactor template rule #get0has-static] 
     */
	public static boolean hasOnrole(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.has(model, instanceResource, ONROLE);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@52d92404 has at least one value set 
     * @return true if this property has at least one value
	 *
	 * [Generated from RDFReactor template rule #get0has-dynamic] 
     */
	public boolean hasOnrole() {
		return Base.has(this.model, this.getResource(), ONROLE);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@52d92404 has the given value (maybe among other values).  
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be checked
     * @return true if this property contains (maybe among other) the given value
	 *
	 * [Generated from RDFReactor template rule #get0has-value-static] 
     */
	public static boolean hasOnrole(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value ) {
		return Base.hasValue(model, instanceResource, ONROLE);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@52d92404 has the given value (maybe among other values).  
	 * @param value the value to be checked
     * @return true if this property contains (maybe among other) the given value
	 *
	 * [Generated from RDFReactor template rule #get0has-value-dynamic] 
     */
	public boolean hasOnrole( org.ontoware.rdf2go.model.node.Node value ) {
		return Base.hasValue(this.model, this.getResource(), ONROLE);
	}

     /**
     * Get all values of property Onrole as an Iterator over RDF2Go nodes 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ClosableIterator of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get7static] 
     */
	public static ClosableIterator<org.ontoware.rdf2go.model.node.Node> getAllOnrole_asNode(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_asNode(model, instanceResource, ONROLE);
	}
	
    /**
     * Get all values of property Onrole as a ReactorResult of RDF2Go nodes 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a List of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get7static-reactor-result] 
     */
	public static ReactorResult<org.ontoware.rdf2go.model.node.Node> getAllOnrole_asNode_(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_as(model, instanceResource, ONROLE, org.ontoware.rdf2go.model.node.Node.class);
	}

    /**
     * Get all values of property Onrole as an Iterator over RDF2Go nodes 
     * @return a ClosableIterator of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get8dynamic] 
     */
	public ClosableIterator<org.ontoware.rdf2go.model.node.Node> getAllOnrole_asNode() {
		return Base.getAll_asNode(this.model, this.getResource(), ONROLE);
	}

    /**
     * Get all values of property Onrole as a ReactorResult of RDF2Go nodes 
     * @return a List of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get8dynamic-reactor-result] 
     */
	public ReactorResult<org.ontoware.rdf2go.model.node.Node> getAllOnrole_asNode_() {
		return Base.getAll_as(this.model, this.getResource(), ONROLE, org.ontoware.rdf2go.model.node.Node.class);
	}
     /**
     * Get all values of property Onrole     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ClosableIterator of $type
	 *
	 * [Generated from RDFReactor template rule #get11static] 
     */
	public static ClosableIterator<SyntacticRole> getAllOnrole(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll(model, instanceResource, ONROLE, SyntacticRole.class);
	}
	
    /**
     * Get all values of property Onrole as a ReactorResult of SyntacticRole 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ReactorResult of $type which can conveniently be converted to iterator, list or array
	 *
	 * [Generated from RDFReactor template rule #get11static-reactorresult] 
     */
	public static ReactorResult<SyntacticRole> getAllOnrole_as(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_as(model, instanceResource, ONROLE, SyntacticRole.class);
	}

    /**
     * Get all values of property Onrole     * @return a ClosableIterator of $type
	 *
	 * [Generated from RDFReactor template rule #get12dynamic] 
     */
	public ClosableIterator<SyntacticRole> getAllOnrole() {
		return Base.getAll(this.model, this.getResource(), ONROLE, SyntacticRole.class);
	}

    /**
     * Get all values of property Onrole as a ReactorResult of SyntacticRole 
     * @return a ReactorResult of $type which can conveniently be converted to iterator, list or array
	 *
	 * [Generated from RDFReactor template rule #get12dynamic-reactorresult] 
     */
	public ReactorResult<SyntacticRole> getAllOnrole_as() {
		return Base.getAll_as(this.model, this.getResource(), ONROLE, SyntacticRole.class);
	}
 
    /**
     * Adds a value to property Onrole as an RDF2Go node 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #add1static] 
     */
	public static void addOnrole( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.add(model, instanceResource, ONROLE, value);
	}
	
    /**
     * Adds a value to property Onrole as an RDF2Go node 
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #add1dynamic] 
     */
	public void addOnrole( org.ontoware.rdf2go.model.node.Node value) {
		Base.add(this.model, this.getResource(), ONROLE, value);
	}
    /**
     * Adds a value to property Onrole from an instance of SyntacticRole 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #add3static] 
     */
	public static void addOnrole(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, SyntacticRole value) {
		Base.add(model, instanceResource, ONROLE, value);
	}
	
    /**
     * Adds a value to property Onrole from an instance of SyntacticRole 
	 *
	 * [Generated from RDFReactor template rule #add4dynamic] 
     */
	public void addOnrole(SyntacticRole value) {
		Base.add(this.model, this.getResource(), ONROLE, value);
	}
  

    /**
     * Sets a value of property Onrole from an RDF2Go node.
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be set
	 *
	 * [Generated from RDFReactor template rule #set1static] 
     */
	public static void setOnrole( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.set(model, instanceResource, ONROLE, value);
	}
	
    /**
     * Sets a value of property Onrole from an RDF2Go node.
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set1dynamic] 
     */
	public void setOnrole( org.ontoware.rdf2go.model.node.Node value) {
		Base.set(this.model, this.getResource(), ONROLE, value);
	}
    /**
     * Sets a value of property Onrole from an instance of SyntacticRole 
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set3static] 
     */
	public static void setOnrole(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, SyntacticRole value) {
		Base.set(model, instanceResource, ONROLE, value);
	}
	
    /**
     * Sets a value of property Onrole from an instance of SyntacticRole 
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set4dynamic] 
     */
	public void setOnrole(SyntacticRole value) {
		Base.set(this.model, this.getResource(), ONROLE, value);
	}
  


    /**
     * Removes a value of property Onrole as an RDF2Go node 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove1static] 
     */
	public static void removeOnrole( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.remove(model, instanceResource, ONROLE, value);
	}
	
    /**
     * Removes a value of property Onrole as an RDF2Go node
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove1dynamic] 
     */
	public void removeOnrole( org.ontoware.rdf2go.model.node.Node value) {
		Base.remove(this.model, this.getResource(), ONROLE, value);
	}
    /**
     * Removes a value of property Onrole given as an instance of SyntacticRole 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove3static] 
     */
	public static void removeOnrole(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, SyntacticRole value) {
		Base.remove(model, instanceResource, ONROLE, value);
	}
	
    /**
     * Removes a value of property Onrole given as an instance of SyntacticRole 
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove4dynamic] 
     */
	public void removeOnrole(SyntacticRole value) {
		Base.remove(this.model, this.getResource(), ONROLE, value);
	}
  
    /**
     * Removes all values of property Onrole     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #removeall1static] 
     */
	public static void removeAllOnrole( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		Base.removeAll(model, instanceResource, ONROLE);
	}
	
    /**
     * Removes all values of property Onrole	 *
	 * [Generated from RDFReactor template rule #removeall1dynamic] 
     */
	public void removeAllOnrole() {
		Base.removeAll(this.model, this.getResource(), ONROLE);
	}
     /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@4313d95e has at least one value set 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return true if this property has at least one value
	 *
	 * [Generated from RDFReactor template rule #get0has-static] 
     */
	public static boolean hasOntriplepart(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.has(model, instanceResource, ONTRIPLEPART);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@4313d95e has at least one value set 
     * @return true if this property has at least one value
	 *
	 * [Generated from RDFReactor template rule #get0has-dynamic] 
     */
	public boolean hasOntriplepart() {
		return Base.has(this.model, this.getResource(), ONTRIPLEPART);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@4313d95e has the given value (maybe among other values).  
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be checked
     * @return true if this property contains (maybe among other) the given value
	 *
	 * [Generated from RDFReactor template rule #get0has-value-static] 
     */
	public static boolean hasOntriplepart(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value ) {
		return Base.hasValue(model, instanceResource, ONTRIPLEPART);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@4313d95e has the given value (maybe among other values).  
	 * @param value the value to be checked
     * @return true if this property contains (maybe among other) the given value
	 *
	 * [Generated from RDFReactor template rule #get0has-value-dynamic] 
     */
	public boolean hasOntriplepart( org.ontoware.rdf2go.model.node.Node value ) {
		return Base.hasValue(this.model, this.getResource(), ONTRIPLEPART);
	}

     /**
     * Get all values of property Ontriplepart as an Iterator over RDF2Go nodes 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ClosableIterator of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get7static] 
     */
	public static ClosableIterator<org.ontoware.rdf2go.model.node.Node> getAllOntriplepart_asNode(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_asNode(model, instanceResource, ONTRIPLEPART);
	}
	
    /**
     * Get all values of property Ontriplepart as a ReactorResult of RDF2Go nodes 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a List of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get7static-reactor-result] 
     */
	public static ReactorResult<org.ontoware.rdf2go.model.node.Node> getAllOntriplepart_asNode_(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_as(model, instanceResource, ONTRIPLEPART, org.ontoware.rdf2go.model.node.Node.class);
	}

    /**
     * Get all values of property Ontriplepart as an Iterator over RDF2Go nodes 
     * @return a ClosableIterator of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get8dynamic] 
     */
	public ClosableIterator<org.ontoware.rdf2go.model.node.Node> getAllOntriplepart_asNode() {
		return Base.getAll_asNode(this.model, this.getResource(), ONTRIPLEPART);
	}

    /**
     * Get all values of property Ontriplepart as a ReactorResult of RDF2Go nodes 
     * @return a List of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get8dynamic-reactor-result] 
     */
	public ReactorResult<org.ontoware.rdf2go.model.node.Node> getAllOntriplepart_asNode_() {
		return Base.getAll_as(this.model, this.getResource(), ONTRIPLEPART, org.ontoware.rdf2go.model.node.Node.class);
	}
     /**
     * Get all values of property Ontriplepart     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ClosableIterator of $type
	 *
	 * [Generated from RDFReactor template rule #get11static] 
     */
	public static ClosableIterator<A_0> getAllOntriplepart(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll(model, instanceResource, ONTRIPLEPART, A_0.class);
	}
	
    /**
     * Get all values of property Ontriplepart as a ReactorResult of A_0 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ReactorResult of $type which can conveniently be converted to iterator, list or array
	 *
	 * [Generated from RDFReactor template rule #get11static-reactorresult] 
     */
	public static ReactorResult<A_0> getAllOntriplepart_as(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_as(model, instanceResource, ONTRIPLEPART, A_0.class);
	}

    /**
     * Get all values of property Ontriplepart     * @return a ClosableIterator of $type
	 *
	 * [Generated from RDFReactor template rule #get12dynamic] 
     */
	public ClosableIterator<A_0> getAllOntriplepart() {
		return Base.getAll(this.model, this.getResource(), ONTRIPLEPART, A_0.class);
	}

    /**
     * Get all values of property Ontriplepart as a ReactorResult of A_0 
     * @return a ReactorResult of $type which can conveniently be converted to iterator, list or array
	 *
	 * [Generated from RDFReactor template rule #get12dynamic-reactorresult] 
     */
	public ReactorResult<A_0> getAllOntriplepart_as() {
		return Base.getAll_as(this.model, this.getResource(), ONTRIPLEPART, A_0.class);
	}
 
    /**
     * Adds a value to property Ontriplepart as an RDF2Go node 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #add1static] 
     */
	public static void addOntriplepart( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.add(model, instanceResource, ONTRIPLEPART, value);
	}
	
    /**
     * Adds a value to property Ontriplepart as an RDF2Go node 
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #add1dynamic] 
     */
	public void addOntriplepart( org.ontoware.rdf2go.model.node.Node value) {
		Base.add(this.model, this.getResource(), ONTRIPLEPART, value);
	}
    /**
     * Adds a value to property Ontriplepart from an instance of A_0 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #add3static] 
     */
	public static void addOntriplepart(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, A_0 value) {
		Base.add(model, instanceResource, ONTRIPLEPART, value);
	}
	
    /**
     * Adds a value to property Ontriplepart from an instance of A_0 
	 *
	 * [Generated from RDFReactor template rule #add4dynamic] 
     */
	public void addOntriplepart(A_0 value) {
		Base.add(this.model, this.getResource(), ONTRIPLEPART, value);
	}
  

    /**
     * Sets a value of property Ontriplepart from an RDF2Go node.
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be set
	 *
	 * [Generated from RDFReactor template rule #set1static] 
     */
	public static void setOntriplepart( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.set(model, instanceResource, ONTRIPLEPART, value);
	}
	
    /**
     * Sets a value of property Ontriplepart from an RDF2Go node.
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set1dynamic] 
     */
	public void setOntriplepart( org.ontoware.rdf2go.model.node.Node value) {
		Base.set(this.model, this.getResource(), ONTRIPLEPART, value);
	}
    /**
     * Sets a value of property Ontriplepart from an instance of A_0 
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set3static] 
     */
	public static void setOntriplepart(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, A_0 value) {
		Base.set(model, instanceResource, ONTRIPLEPART, value);
	}
	
    /**
     * Sets a value of property Ontriplepart from an instance of A_0 
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set4dynamic] 
     */
	public void setOntriplepart(A_0 value) {
		Base.set(this.model, this.getResource(), ONTRIPLEPART, value);
	}
  


    /**
     * Removes a value of property Ontriplepart as an RDF2Go node 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove1static] 
     */
	public static void removeOntriplepart( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.remove(model, instanceResource, ONTRIPLEPART, value);
	}
	
    /**
     * Removes a value of property Ontriplepart as an RDF2Go node
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove1dynamic] 
     */
	public void removeOntriplepart( org.ontoware.rdf2go.model.node.Node value) {
		Base.remove(this.model, this.getResource(), ONTRIPLEPART, value);
	}
    /**
     * Removes a value of property Ontriplepart given as an instance of A_0 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove3static] 
     */
	public static void removeOntriplepart(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, A_0 value) {
		Base.remove(model, instanceResource, ONTRIPLEPART, value);
	}
	
    /**
     * Removes a value of property Ontriplepart given as an instance of A_0 
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove4dynamic] 
     */
	public void removeOntriplepart(A_0 value) {
		Base.remove(this.model, this.getResource(), ONTRIPLEPART, value);
	}
  
    /**
     * Removes all values of property Ontriplepart     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #removeall1static] 
     */
	public static void removeAllOntriplepart( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		Base.removeAll(model, instanceResource, ONTRIPLEPART);
	}
	
    /**
     * Removes all values of property Ontriplepart	 *
	 * [Generated from RDFReactor template rule #removeall1dynamic] 
     */
	public void removeAllOntriplepart() {
		Base.removeAll(this.model, this.getResource(), ONTRIPLEPART);
	}
     /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@54c90c7 has at least one value set 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return true if this property has at least one value
	 *
	 * [Generated from RDFReactor template rule #get0has-static] 
     */
	public static boolean hasSub_mapping(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.has(model, instanceResource, SUB_MAPPING);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@54c90c7 has at least one value set 
     * @return true if this property has at least one value
	 *
	 * [Generated from RDFReactor template rule #get0has-dynamic] 
     */
	public boolean hasSub_mapping() {
		return Base.has(this.model, this.getResource(), SUB_MAPPING);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@54c90c7 has the given value (maybe among other values).  
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be checked
     * @return true if this property contains (maybe among other) the given value
	 *
	 * [Generated from RDFReactor template rule #get0has-value-static] 
     */
	public static boolean hasSub_mapping(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value ) {
		return Base.hasValue(model, instanceResource, SUB_MAPPING);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@54c90c7 has the given value (maybe among other values).  
	 * @param value the value to be checked
     * @return true if this property contains (maybe among other) the given value
	 *
	 * [Generated from RDFReactor template rule #get0has-value-dynamic] 
     */
	public boolean hasSub_mapping( org.ontoware.rdf2go.model.node.Node value ) {
		return Base.hasValue(this.model, this.getResource(), SUB_MAPPING);
	}

     /**
     * Get all values of property Sub_mapping as an Iterator over RDF2Go nodes 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ClosableIterator of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get7static] 
     */
	public static ClosableIterator<org.ontoware.rdf2go.model.node.Node> getAllSub_mapping_asNode(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_asNode(model, instanceResource, SUB_MAPPING);
	}
	
    /**
     * Get all values of property Sub_mapping as a ReactorResult of RDF2Go nodes 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a List of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get7static-reactor-result] 
     */
	public static ReactorResult<org.ontoware.rdf2go.model.node.Node> getAllSub_mapping_asNode_(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_as(model, instanceResource, SUB_MAPPING, org.ontoware.rdf2go.model.node.Node.class);
	}

    /**
     * Get all values of property Sub_mapping as an Iterator over RDF2Go nodes 
     * @return a ClosableIterator of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get8dynamic] 
     */
	public ClosableIterator<org.ontoware.rdf2go.model.node.Node> getAllSub_mapping_asNode() {
		return Base.getAll_asNode(this.model, this.getResource(), SUB_MAPPING);
	}

    /**
     * Get all values of property Sub_mapping as a ReactorResult of RDF2Go nodes 
     * @return a List of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get8dynamic-reactor-result] 
     */
	public ReactorResult<org.ontoware.rdf2go.model.node.Node> getAllSub_mapping_asNode_() {
		return Base.getAll_as(this.model, this.getResource(), SUB_MAPPING, org.ontoware.rdf2go.model.node.Node.class);
	}
     /**
     * Get all values of property Sub_mapping     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ClosableIterator of $type
	 *
	 * [Generated from RDFReactor template rule #get11static] 
     */
	public static ClosableIterator<Mapping> getAllSub_mapping(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll(model, instanceResource, SUB_MAPPING, Mapping.class);
	}
	
    /**
     * Get all values of property Sub_mapping as a ReactorResult of Mapping 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ReactorResult of $type which can conveniently be converted to iterator, list or array
	 *
	 * [Generated from RDFReactor template rule #get11static-reactorresult] 
     */
	public static ReactorResult<Mapping> getAllSub_mapping_as(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_as(model, instanceResource, SUB_MAPPING, Mapping.class);
	}

    /**
     * Get all values of property Sub_mapping     * @return a ClosableIterator of $type
	 *
	 * [Generated from RDFReactor template rule #get12dynamic] 
     */
	public ClosableIterator<Mapping> getAllSub_mapping() {
		return Base.getAll(this.model, this.getResource(), SUB_MAPPING, Mapping.class);
	}

    /**
     * Get all values of property Sub_mapping as a ReactorResult of Mapping 
     * @return a ReactorResult of $type which can conveniently be converted to iterator, list or array
	 *
	 * [Generated from RDFReactor template rule #get12dynamic-reactorresult] 
     */
	public ReactorResult<Mapping> getAllSub_mapping_as() {
		return Base.getAll_as(this.model, this.getResource(), SUB_MAPPING, Mapping.class);
	}
 
    /**
     * Adds a value to property Sub_mapping as an RDF2Go node 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #add1static] 
     */
	public static void addSub_mapping( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.add(model, instanceResource, SUB_MAPPING, value);
	}
	
    /**
     * Adds a value to property Sub_mapping as an RDF2Go node 
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #add1dynamic] 
     */
	public void addSub_mapping( org.ontoware.rdf2go.model.node.Node value) {
		Base.add(this.model, this.getResource(), SUB_MAPPING, value);
	}
    /**
     * Adds a value to property Sub_mapping from an instance of Mapping 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #add3static] 
     */
	public static void addSub_mapping(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, Mapping value) {
		Base.add(model, instanceResource, SUB_MAPPING, value);
	}
	
    /**
     * Adds a value to property Sub_mapping from an instance of Mapping 
	 *
	 * [Generated from RDFReactor template rule #add4dynamic] 
     */
	public void addSub_mapping(Mapping value) {
		Base.add(this.model, this.getResource(), SUB_MAPPING, value);
	}
  

    /**
     * Sets a value of property Sub_mapping from an RDF2Go node.
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be set
	 *
	 * [Generated from RDFReactor template rule #set1static] 
     */
	public static void setSub_mapping( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.set(model, instanceResource, SUB_MAPPING, value);
	}
	
    /**
     * Sets a value of property Sub_mapping from an RDF2Go node.
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set1dynamic] 
     */
	public void setSub_mapping( org.ontoware.rdf2go.model.node.Node value) {
		Base.set(this.model, this.getResource(), SUB_MAPPING, value);
	}
    /**
     * Sets a value of property Sub_mapping from an instance of Mapping 
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set3static] 
     */
	public static void setSub_mapping(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, Mapping value) {
		Base.set(model, instanceResource, SUB_MAPPING, value);
	}
	
    /**
     * Sets a value of property Sub_mapping from an instance of Mapping 
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set4dynamic] 
     */
	public void setSub_mapping(Mapping value) {
		Base.set(this.model, this.getResource(), SUB_MAPPING, value);
	}
  


    /**
     * Removes a value of property Sub_mapping as an RDF2Go node 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove1static] 
     */
	public static void removeSub_mapping( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.remove(model, instanceResource, SUB_MAPPING, value);
	}
	
    /**
     * Removes a value of property Sub_mapping as an RDF2Go node
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove1dynamic] 
     */
	public void removeSub_mapping( org.ontoware.rdf2go.model.node.Node value) {
		Base.remove(this.model, this.getResource(), SUB_MAPPING, value);
	}
    /**
     * Removes a value of property Sub_mapping given as an instance of Mapping 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove3static] 
     */
	public static void removeSub_mapping(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, Mapping value) {
		Base.remove(model, instanceResource, SUB_MAPPING, value);
	}
	
    /**
     * Removes a value of property Sub_mapping given as an instance of Mapping 
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove4dynamic] 
     */
	public void removeSub_mapping(Mapping value) {
		Base.remove(this.model, this.getResource(), SUB_MAPPING, value);
	}
  
    /**
     * Removes all values of property Sub_mapping     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #removeall1static] 
     */
	public static void removeAllSub_mapping( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		Base.removeAll(model, instanceResource, SUB_MAPPING);
	}
	
    /**
     * Removes all values of property Sub_mapping	 *
	 * [Generated from RDFReactor template rule #removeall1dynamic] 
     */
	public void removeAllSub_mapping() {
		Base.removeAll(this.model, this.getResource(), SUB_MAPPING);
	}
 }